### ISSUE TITLE
nginx-exporter not running

### ISSUE THREAD

**Issue by azeng528** [nginxinc/nginx-prometheus-exporter#192]
**Describe the bug**
![image](https://user-images.githubusercontent.com/19300752/118604353-a6e0a280-b7e7-11eb-9b0c-203e7a006b3e.png)

如上图所示

docker_run.sh

docker run -d --name nginx-exporter -h nginx-exporter \
    -v /etc/localtime:/etc/localtime \
    --network host \
    --restart=always \
    nginx/nginx-prometheus-exporter:0.9.0 -nginx.scrape-uri=http://127.0.0.1:9098/basic_status

**Comment by luisgarcia1010** [comment]
the problem is that you want to connect from the container at 127.0.0.1, the container does not have port 9098 to 127.0.0.1, you need to change `-nginx.scrape-uri=http://127.0.0.1:9098/basic_status` to `-nginx.scrape-uri=http://real_ip:9098/basic_status` or `-nginx.scrape-uri=http://mydomain.com:9098/basic_status`
