### ISSUE TITLE
NGINX Plus upstream state mapping doesn't conform with Prometheus conventions

### ISSUE THREAD

**Issue by nielsole** [nginxinc/nginx-prometheus-exporter#35]
When using the `nginxplus_upstream_server_state` it is frustrating, that the different states are integers. This makes it hard to do a `count(nginxplus_upstream_server_state) group by (upstream, state)` query(e.g. for multiple loadbalancers) in prometheus.

**Describe the solution you'd like**
It is far more common in prometheus, to have different timeseries for different statuses as long as they have an upper bound. This is also the way upstream error codes are currently handled.

**Additional context**
upstreamServerStates mapping:
https://github.com/nginxinc/nginx-prometheus-exporter/blob/65702758f28e7f472fa3a978d9321ee3cb9a7d2c/collector/nginx_plus.go#L294

How status codes are handled:
https://github.com/nginxinc/nginx-prometheus-exporter/blob/65702758f28e7f472fa3a978d9321ee3cb9a7d2c/collector/nginx_plus.go#L175

Is there a reason such a mapping to integers was chosen?

**Comment by pleshakov** [comment]
@nielsole 
are you trying to query how many up or down upstream servers in a particular upstream? for such queries you can use the following Prometheus queries:

number of up upstream servers (in the "up" or "draining" state):
```
count(nginxplus_upstream_server_state < 3) by (upstream, server)
```

number of down upstream servers (in the "down", "unavail", "checking" or "unhealthy" state):
```
count(nginxplus_upstream_server_state > 2) by (upstream, server)
``` 
Taken from https://github.com/nginxinc/nginx-prometheus-exporter/issues/21

Can the approach below solve your problem?

> Is there a reason such a mapping to integers was chosen?

Yes, an upstream server can only be in one of 6 states at a point of time. thus, instead of having  6 different metrics (or one metric with 6 labels), where one is set to 1 and the rest to 0, we decided to have one metric which can have 6 different values.
