### ISSUE TITLE
Parameter to avoid service stop in case the scrape target is not reachable

### ISSUE THREAD

**Issue by ttoossaa** [nginxinc/nginx-prometheus-exporter#36]
Hi,

I would like to use your nginx-prometheus-exporter as a sidecar container in kubernetes to collect metrics from a nginx container running in the same Pod.
Unfortunately the nginx container needs ~1-2 seconds to start. So the scrape target for the nginx-prometheus-exporter is not reachable when it starts. Therefore the exporter stops and the container has to be restarted from kubernetes. After the container restart, the exporter is working fine because the nginx process was able to start in the meantime and the scrape target is reachable then.

So I would like to ask if it would be possible to add a parameter to the exporter to avoid the default behavior of stopping. A simple sleep and retry after a specific time (maybe 5s) would be very useful.

_The related error log output:_
```
root@k8s [dc]:~# kubectl logs $pod -c prometheus-exporter  -p

2019/02/20 11:42:51 Starting NGINX Prometheus Exporter Version=0.3.0 GitCommit=6570275
2019/02/20 11:42:51 Could not create Nginx Client: Failed to create NginxClient: failed to get http://127.0.0.1:8080/stub_status: Get http://127.0.0.1:8080/stub_status: dial tcp 127.0.0.1:8080: connect: connection refused
```

Thank you.

**Comment by pleshakov** [comment]
@ttoossaa Thanks for sharing.

Are you running NGINX or NGINX with the [Ingress Controller](https://github.com/nginxinc/kubernetes-ingress/)? For the latter case, we're planning to start running the exporter in the IC binary, instead of running it in a separate container, which will solve this issue.

For the former case,
Do you think the following additional parameters could address the issue?
* `-nginx.retries` A number of retries the exporter will make on start to connect to the NGINX stub_status page/NGINX Plus API before giving up and exiting with an error.
* `-nginx.retry-interval` An interval between retries to connect to the NGINX stub_status page/NGINX Plus API on start.

Additionally, do you think the following workaround could address your issue? Here we replaced the default entry point with a new one that launches a few commands:
```yaml
    args:
    - -c
    - echo "sleeping for 5s" && sleep 5 && /usr/bin/exporter -web.listen-address :9113 -nginx.scrape-uri http://127.0.0.1:8080/stub_status
    command:
    - /bin/sh
```

**Comment by ttoossaa** [comment]
Hi @pleshakov,

thank you for your quick reply. I'm running a nginx without the ingress controller.

I was also thinking about a workaround as you mentioned it. So it would do the job but has some disadvantages in my opinion. The first process in the docker container would be the `sh` binary. So all signals from kubernetes (e.g. SIGTERM for a graceful shutdown) to the container would not reach the prometheus-exporter binary because the `sh` command wouldn't forward it. The startup time of the Pod would be also increased because kubernetes forwards traffic only to Pods where all containers are ready.

So I think the solution you mentioned with the parameters `-nginx.retries` and `-nginx.retry-interval` would be the best solution and address the issue totally.

**Comment by pleshakov** [comment]
@ttoossaa 
in this specific case, the exporter  becomes PID 1 after 5s. The startup time of the pod doesn't increase as well - the exporter container is considered ready once the script is running.

thanks, we'll add the parameters.

**Comment by ttoossaa** [comment]
Thank you!
