### ISSUE TITLE
last reload

### ISSUE THREAD

**Issue by Toutzn** [nginxinc/nginx-prometheus-exporter#53]
Hi,

could you please add a value which has timestamp last reload Nginx? like:

curl -s '127.0.0.1/api/4/nginx' | jq
{
  "version": "1.15.10",
  "build": "nginx-plus-r18",
  "address": "127.0.0.1",
  "generation": 7,
  "load_timestamp": "2019-05-30T11:15:03.206Z",
  "timestamp": "2019-05-30T11:44:16.317Z",
  "pid": 60024,
  "ppid": 31797
}

Also I can use the rest of values like version, build etc.

Tanks a lot

**Comment by pleshakov** [comment]
@Toutzn 
Thanks for the feature request!

We will shortly release an alternative Prometheus exporter implementation that uses [njs](https://nginx.org/en/docs/njs/). The njs exporter runs as part of NGINX Plus rather than as a sidecar process/Docker container, which is how the go exporter is deployed. As a result, the njs exporter should be much easier to install, configure and extend, and we will recommend it going forward. However, we will continue to maintain the go exporter because we rely on it in our [Ingress Controller ](https://github.com/nginxinc/kubernetes-ingress/) project.

I'd like to revisit your request once we've released the njs version.

**Comment by Toutzn** [comment]
Ok. is it compatible with FreeBSD? we are running Nginx plus on FreeBSD 12.0 also the nginx_exporter.

Thanks

**Comment by pleshakov** [comment]
the njs implementation will be compatible with FreeBSD.

We haven't tested that, but the go-based implementation should be compatible. However, we don't provide any binaries for FreeBSD, so you need to build the binary https://github.com/nginxinc/nginx-prometheus-exporter#building-the-binary

**Comment by Nklya** [comment]
Looks like it's already released https://docs.nginx.com/nginx/admin-guide/dynamic-modules/prometheus-njs/

**Comment by Dean-Coakley** [comment]
Closing as last reload is implemented in the njs implementation.
