### ISSUE TITLE
Metric for cache

### ISSUE THREAD

**Issue by andywow** [nginxinc/nginx-prometheus-exporter#54]
Can you add metrics for nginx cache? I see that metrics already exists via "/api/4/http/caches" nginx url.

**Comment by pleshakov** [comment]
@andywow 
Thanks for the feature request!

We will shortly release an alternative Prometheus exporter implementation that uses [njs](https://nginx.org/en/docs/njs/). The njs exporter runs as part of NGINX Plus rather than as a sidecar process/Docker container, which is how the go exporter is deployed. As a result, the njs exporter should be much easier to install, configure and extend, and we will recommend it going forward. However, we will continue to maintain the go exporter because we rely on it in our [Ingress Controller](https://github.com/nginxinc/kubernetes-ingress/) project.

I'd like to revisit your request once we've released the njs version.

**Comment by Nklya** [comment]
Looks like it's already released https://docs.nginx.com/nginx/admin-guide/dynamic-modules/prometheus-njs/

**Comment by andywow** [comment]
Yes, but there are no cache metrics in prometheus-njs module too

**Comment by Nklya** [comment]
Yeah, and Grafana dashboard for Nginx plus still absent too 😿😢😿

**Comment by Dean-Coakley** [comment]
Closing. Cache metrics are available in prometheus-njs module: https://docs.nginx.com/nginx/admin-guide/dynamic-modules/prometheus-njs/
