### ISSUE TITLE
Wrong Nginx compatibility version on releases page

### ISSUE THREAD

**Issue by Nklya** [nginxinc/nginx-prometheus-exporter#58]
**Describe the bug**
Every release note contains the wrong compatibility version  at https://github.com/nginxinc/nginx-prometheus-exporter/releases
```
COMPATIBILITY:
NGINX 0.1.18 or newer.
```
While 0.16 is the last stable

**To reproduce**
1. Open releases page https://github.com/nginxinc/nginx-prometheus-exporter/releases
2. Check any release

**Expected behavior**
Release notes contains correct compatibility version

**Comment by Rulox** [comment]
Hi @Nklya

NGINX `0.1.18`  is the minimum version of NGINX OSS required to make the exporter works. That's why we say 0.1.18 **or newer**. This is intended, to make sure users know which versions they can use. It's up to the user to keep their version updated, but at least we let them know that this exporter works with older versions too (above 0.1.18).

The reason of choosing `0.1.18` it's because that's the version where the [stub_status](http://nginx.org/en/docs/http/ngx_http_stub_status_module.html#stub_status) module was added.

Please let me know if this makes sense to you.

**Comment by Nklya** [comment]
Oh, thank you.

Sorry, I haven't noticed zero in the beginning of `0.1.18`.
