### ISSUE TITLE
CONST_LABELS and -prometheus.const-labels are not working 

### ISSUE THREAD

**Issue by shootkin** [nginxinc/nginx-prometheus-exporter#83]
**Describe the bug**
When I set CONST_LABELS, it does not make any effect . When I try to set -prometheus.const-labels, it produces an error.

**To reproduce**
1. `docker run -e CONST_LABELS=blabla=blabla -it nginx/nginx-prometheus-exporter:0.5.0 -nginx.scrape-uri http://hostname/basic_status`
2. Go to container_ip:9113/metrics
3. See metrics without label(s) passed before

OR

1. `docker run -it nginx/nginx-prometheus-exporter:0.5.0 -nginx.scrape-uri http://hostname/basic_status -prometheus.const-labels blabla=blabla`
2. See error: `flag provided but not defined: -prometheus.const-labels`

**Expected behavior**
Metrics are shown with labels.

**Your environment**
* Version of the Prometheus exporter: gitCommit="c3dd65c",version="0.5.0"
* Version of Docker/Kubernetes: Docker version 18.09.6, build 481bc77
* Using NGINX

**Comment by Dean-Coakley** [comment]
Hi @shootkin 

Const labels support was added in https://github.com/nginxinc/nginx-prometheus-exporter/commit/c699f2297fde870ebfaa8c08bcec87af1f4b6dca but there hasn't been a release published since then.

To use `CONST_LABELS`. You must build the container and push to your registry. https://github.com/nginxinc/nginx-prometheus-exporter#building-the-exporter

Const labels will be included in the next major release of the prometheus exporter.

Hope that helps!

**Comment by shootkin** [comment]
> Hi @shootkin
> 
> Const labels support was added in [c699f22](https://github.com/nginxinc/nginx-prometheus-exporter/commit/c699f2297fde870ebfaa8c08bcec87af1f4b6dca) but there hasn't been a release published since then.
> 
> To use `CONST_LABELS`. You must build the container and push to your registry. https://github.com/nginxinc/nginx-prometheus-exporter#building-the-exporter
> 
> Const labels will be included in the next major release of the prometheus exporter.
> 
> Hope that helps!

Yes, it works! Thank you!
