### ISSUE TITLE
Is is good to monitor the number of dropped Nginx connection?

### ISSUE THREAD

**Issue by boseabhishek** [nginxinc/nginx-prometheus-exporter#88]
**Describe the solution you'd like**
It is worthwhile to know the number/graph of dropped connections for Nginx e.g. `nginx_connections_dropped`

**Describe alternatives you've considered**
This can be retrieved from (accepted-handled) with PromQL in Prometheus/Grafana.

**Comment by pleshakov** [comment]
Hi @boseabhishek 

The alternative you provided seems reasonable to me.

The exporter doesn't calculate any new metrics - it just converts the existing metrics from NGINX (or NGINX Plus) format to the Prometheus format.

**Comment by boseabhishek** [comment]
Thanks... one quick question - have you used dropped ever? Is it sum(accepted) - sum(handled)? I can’t get anything out..

**Comment by pleshakov** [comment]
In Prometheus, it should be `nginx_connections_accepted - nginx_connections_handled` Note that it would be `0` most of the time. Unless NGINX started dropping connections, because, for example, the number of connections exceeds the value of this directive http://nginx.org/en/docs/ngx_core_module.html#worker_connections

**Comment by boseabhishek** [comment]
I get 0 all the time. Thanks for your reply.
