### ISSUE TITLE
How to use this exporter for Prometheus Metrics ?

### ISSUE THREAD

**Issue by arpitjindal97** [nginxinc/nginx-prometheus-exporter#93]
I can see Nginx throws 2 types of Monitoring Logs:

 - [Stub Status](https://docs.nginx.com/nginx-ingress-controller/logging-and-monitoring/status-page/)
 - [Prometheus Metrics](https://docs.nginx.com/nginx-ingress-controller/logging-and-monitoring/prometheus/)

Only Stub Status is being considered here. I can setup 2 services to get those in 1 Prometheus Server, but I still have some following doutbts:

 - Why Prometheus Metrics are not considered ?
 - Why Nginx is throwing 2 different metrics ?
 - How to combine them together ?
 - Are there any future plan to include Prometheus Metrics in this too ?

**Comment by Rulox** [comment]
Hi @arpitjindal97 

The documentation you refer is about the [NGINX Ingress Controller](https://github.com/nginxinc/kubernetes-ingress) metrics. This project is the NGINX Prometheus Exporter. If you use the exporter as a container/binary, you will only see `stub_status` metrics (or NGINX Plus metrics) because this has nothing to do with the Ingress Controller, only with NGINX metrics.

I am going to assume you are using the Ingress Controller:

 If you read the [Available Metrics section](https://docs.nginx.com/nginx-ingress-controller/logging-and-monitoring/prometheus/#available-metrics) you will notice that there are 2 main points. The first one says that NGINX metrics are exported in Prometheus format (these are the `stub_status` or NGINX Plus API metrics), and the second one are custom Ingress Controller metrics. So, in conclusion:

* If you use the NGINX Prometheus Exporter in your environment, you will only see the first metrics (`stub_status`)
* If you are using the NGINX Ingress Controller and enable metrics, additionally to the `stub_status` metrics, you will see custom Ingress Controller metrics that are related to the Ingress Controller.

I don't fully understand your question, so I hope this clarifies your concerns. Let me know if you have any more questions, thanks.

**Comment by arpitjindal97** [comment]
Thanks @Rulox, you have clarified my doubts, just one thing is left. 

Is there any cleaner way to combine Ingress Metrics and Nginx Metrics into one ?

For example: Seeing both the metrics using this exporter

**Comment by Rulox** [comment]
You can see all the metrics from 1 place with the Ingress Controller. You don't need to use the Exporter at all.

Enable the metrics following the [docs](https://docs.nginx.com/nginx-ingress-controller/logging-and-monitoring/prometheus/#enabling-metrics) and you will see all the metrics (nginx and ingress) in the same endpoint `/metrics` in your Ingress Controller pod.

Makes sense?
